In [137]:
import numpy as np
import pandas as pd

In [138]:
## merging two dataframes
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'salary': [10000, 20000, 30000, 40000],
    'bonus': [5000, 6000, 7000, 8000]
})


salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 4],
    'salary': [10000, 20000, 30000, 40000],
    'bonus': [5000, 6000, 7000, 8000]
})

In [139]:
employees

   employee_id  salary  bonus
0            1   10000   5000
1            2   20000   6000
2            3   30000   7000
3            4   40000   8000

In [140]:
print(salaries)

   employee_id  salary  bonus
0            1   10000   5000
1            2   20000   6000
2            3   30000   7000
3            4   40000   8000

In [141]:
pd.merge(employees, salaries, on='employee_id', how='inner')
## ham yaha par ham 2 dataframe ko merge kar rahi hai aur employee_id ke basices par ham
##ander me jo employee_id hai uske ko common id hai uske basis par merage karega dataframe ko

   employee_id  salary_x  bonus_x  salary_y  bonus_y
0            1     10000     5000     10000     5000
1            2     20000     6000     20000     6000
2            3     30000     7000     30000     7000
3            4     40000     8000     40000     8000

In [142]:
pd.merge(employees, salaries, on='employee_id', how='outer')

   employee_id  salary_x  bonus_x  salary_y  bonus_y
0            1     10000     5000     10000     5000
1            2     20000     6000     20000     6000
2            3     30000     7000     30000     7000
3            4     40000     8000     40000     8000

In [143]:
##Contation of two dataframe
df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2', 'A3'],
    'B':['B0', 'B1', 'B2', 'B3'],
    'C': ['C0', 'C1', 'C2', 'C3'],
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5', 'A6'],
    'B': ['B3', 'B4', 'B5', 'B6'],
    'C': ['C3', 'C4', 'C5', 'C6'],
})

In [144]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3

In [145]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
3  A6  B6  C6

In [146]:
pd.concat([df1, df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
3  A3  B3  C3
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5
3  A6  B6  C6

In [147]:
pd.concat([df1, df2], axis=1) ##we are concat the basis of row

    A   B   C   A   B   C
0  A0  B0  C0  A3  B3  C3
1  A1  B1  C1  A4  B4  C4
2  A2  B2  C2  A5  B5  C5
3  A3  B3  C3  A6  B6  C6

In [148]:
##Joining of two dataframe

##first dataframe
df1 = pd.DataFrame({
    'name':['Alice', 'Bob', 'Charlie'],
}, index=[1, 2, 3])

##second dataframe
df2 = pd.DataFrame({
    'score': [85, 92, 78]
}, index=[2,3,4])

In [149]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [150]:
df2

   score
2     85
3     92
4     78

In [151]:
df1.join(df2, how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   92.0
4      NaN   78.0

In [152]:
df2.join(df1, how='outer')

   score     name
1    NaN    Alice
2   85.0      Bob
3   92.0  Charlie
4   78.0      NaN