In [89]:
##Creating a Dartaframe

In [90]:
##sudo apt install python3-venv
##python3 -m venv venv
##source venv/bin/activate

In [91]:
import numpy as np
import pandas as pd

In [92]:
data= {
    'Name':['Jhon', 'Anna', 'Peter', 'Linda'],
    'Location':['New York', 'Paris', 'Berlin', 'London'],
    'Age':[24, 13, 53, 33],
    'Status':['Single', 'Married', 'Married', 'Single'],
    'Salary':[10000, 20000, 15000, 30000]
}

df = pd.DataFrame(data)## ye data ko dataframe me convert karega jo nice looking hai

In [93]:
df ## yaha par ham use kar rhai hai

    Name  Location  Age   Status  Salary
0   Jhon  New York   24   Single   10000
1   Anna     Paris   13  Married   20000
2  Peter    Berlin   53  Married   15000
3  Linda    London   33   Single   30000

In [94]:
data_list = [
    ['Jhon', 'New York', 24, 'Single', 10000],
    ['Anna', 'Paris', 13, 'Married', 20000],
    ['Peter', 'Berlin', 53, 'Married', 15000],
    ['Linda', 'London', 33, 'Single', 30000]
]

df2 = pd.DataFrame(data_list)
columns = ['Name', 'Location', 'Age', 'Status', 'Salary']## ham yaha par ye column ka data ko ham data_list me set kar rahi hai 
df2 = pd.DataFrame(data_list, columns=columns)## jo Datafrom ke roop me show hoga
print(df2)

    Name  Location  Age   Status  Salary
0   Jhon  New York   24   Single   10000
1   Anna     Paris   13  Married   20000
2  Peter    Berlin   53  Married   15000
3  Linda    London   33   Single   30000

In [95]:
df2## yaha par ham use kar rahi hai

    Name  Location  Age   Status  Salary
0   Jhon  New York   24   Single   10000
1   Anna     Paris   13  Married   20000
2  Peter    Berlin   53  Married   15000
3  Linda    London   33   Single   30000

In [96]:
df['Name'] ## yaha par ham iska column ka name pass kar ke ham uske data ko shoow kar te hai na ki indexing number ko pass kar ke

0     Jhon
1     Anna
2    Peter
3    Linda
Name: Name, dtype: object

In [97]:
df2[['Name', 'Age']]##access the 2 column at a time

    Name  Age
0   Jhon   24
1   Anna   13
2  Peter   53
3  Linda   33

In [98]:
df2['Designation'] = ['Doctor', 'Eng', 'Doctor', 'Eng.']
df2 ## yese ham new column ko add kar

    Name  Location  Age   Status  Salary Designation
0   Jhon  New York   24   Single   10000      Doctor
1   Anna     Paris   13  Married   20000         Eng
2  Peter    Berlin   53  Married   15000      Doctor
3  Linda    London   33   Single   30000        Eng.

In [99]:
## axis 1 ka matlab hai ki ------------------------ direction me operation hoga
## axis 0 ka matlab hai ki iska opposite direction me ham iska operation karenge

In [100]:
df2.drop('Designation', axis = 1)## iska use ham column ka name ko lik kar ham uss column ka position ko Axis-1 ko set kar ke ham usme
##delte kar te
###Column ko remove karega

    Name  Location  Age   Status  Salary
0   Jhon  New York   24   Single   10000
1   Anna     Paris   13  Married   20000
2  Peter    Berlin   53  Married   15000
3  Linda    London   33   Single   30000

In [101]:
df2.drop(0,axis = 0)## ye (0) ka name ha jo isme ham usko row wise ham delete karenge

    Name Location  Age   Status  Salary Designation
1   Anna    Paris   13  Married   20000         Eng
2  Peter   Berlin   53  Married   15000      Doctor
3  Linda   London   33   Single   30000        Eng.

In [102]:
df2.loc[[0,1]]## give the data from indexing

   Name  Location  Age   Status  Salary Designation
0  Jhon  New York   24   Single   10000      Doctor
1  Anna     Paris   13  Married   20000         Eng

In [103]:
##Selecting Subsets of Rows and Columns

df.loc[[0,1]]

   Name  Location  Age   Status  Salary
0  Jhon  New York   24   Single   10000
1  Anna     Paris   13  Married   20000

In [104]:
## I only want to whose age is above 30 and their location must be Paris



df2[(df2['Age'] > 30) & (df2['Location'] == 'Paris')]

Empty DataFrame
Columns: [Name, Location, Age, Status, Salary, Designation]
Index: []

In [105]:
## I only want to whose age is above 30 and their location must be Paris

df2[(df2['Age'] > 30) & (df2['Location'] == 'Paris')]

Empty DataFrame
Columns: [Name, Location, Age, Status, Salary, Designation]
Index: []