In [52]:
##sudo apt install python3-venv
##python3 -m venv venv
##source venv/bin/activate

In [53]:
import numpy as np
import pandas as pd

In [54]:
data = {
    'A': [1,2,np.nan,4,5],## nan ka matlab hai ki wo null value hai
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan, np.nan,5]
}

df = pd.DataFrame(data)

In [55]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [56]:
df.isna() ## used to print the null value and actual values in a from of true or false

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [57]:
df.isna().sum() ## used to count the null value

A    1
B    0
C    2
D    3
dtype: int64

In [58]:
df.isna().any()## deaga ki kon kon sa me null value hai hai ya nahi to true or false return karega

A     True
B    False
C     True
D     True
dtype: bool

In [59]:
df.dropna()## yaha par ham null value ko delete karenge

     A  B    C    D
0  1.0  1  1.0  1.0

In [ ]:
df.dropna(thresh=3) ## ye check karega ki data me kam se kam three null value hai ya nahi hoga to usko remove karega

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

In [61]:
df.fillna(0) ## yaha par ham null value ko 0 se replace karenge

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [ ]:
values = {'A': 0, 'B':100, 'C':300, 'D':400}
df.fillna(values)## tah par ham column wise data ko fill kar rahi hai

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

In [65]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0